# Generated by Django 5.0.2 on 2024-03-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient'], 'verbose_name': 'ingredient', 'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('ingredient', 'quantity', 'recipe')},
        ),
    ]
