# Generated by Django 5.0.2 on 2024-03-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
    ]
