# Generated by Django 5.0.2 on 2024-03-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={},
        ),
    ]
